services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www
    working_dir: /var/www
    entrypoint: ["sh", "/var/www/docker/entrypoint.sh"]
    command: ["php-fpm"]
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    ports:
      - "8006:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8007:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password     

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
  